// lib/abis/aave-v3.ts
export const UI_POOL_DATA_PROVIDER_ABI = [
    {
        inputs: [
            { internalType: 'address', name: 'user', type: 'address' }
        ],
        name: 'getUserReservesData',
        outputs: [
            {
                components: [
                    { internalType: 'address', name: 'underlyingAsset', type: 'address' },
                    { internalType: 'uint256', name: 'scaledATokenBalance', type: 'uint256' },
                    { internalType: 'uint256', name: 'currentATokenBalance', type: 'uint256' },
                    { internalType: 'uint256', name: 'scaledVariableDebt', type: 'uint256' },
                    { internalType: 'uint256', name: 'currentVariableDebt', type: 'uint256' },
                    { internalType: 'uint256', name: 'principalStableDebt', type: 'uint256' },
                    { internalType: 'uint256', name: 'currentStableDebt', type: 'uint256' },
                    { internalType: 'uint256', name: 'currentTotalDebt', type: 'uint256' },
                    { internalType: 'uint256', name: 'stableBorrowRate', type: 'uint256' },
                    { internalType: 'uint256', name: 'liquidityRate', type: 'uint256' },
                    { internalType: 'uint40', name: 'stableRateLastUpdated', type: 'uint40' },
                    { internalType: 'bool', name: 'usageAsCollateralEnabled', type: 'bool' },
                ],
                internalType: 'struct IUiPoolDataProvider.UserReserveData[]',
                name: '',
                type: 'tuple[]',
            },
            {
                components: [
                    { internalType: 'uint256', name: 'currentLiquidationThreshold', type: 'uint256' },
                    { internalType: 'uint256', name: 'ltv', type: 'uint256' },
                    { internalType: 'uint256', name: 'healthFactor', type: 'uint256' },
                ],
                internalType: 'struct IUiPoolDataProvider.AggregatedReserveData[]',
                name: '',
                type: 'tuple[]',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
    {
        inputs: [
            { internalType: 'address', name: 'user', type: 'address' }
        ],
        name: 'getReservesData',
        outputs: [
            {
                components: [
                    { internalType: 'address', name: 'underlyingAsset', type: 'address' },
                    { internalType: 'string', name: 'name', type: 'string' },
                    { internalType: 'string', name: 'symbol', type: 'string' },
                    { internalType: 'uint256', name: 'decimals', type: 'uint256' },
                    { internalType: 'uint256', name: 'baseLTVasCollateral', type: 'uint256' },
                    { internalType: 'uint256', name: 'reserveLiquidationThreshold', type: 'uint256' },
                    { internalType: 'uint256', name: 'reserveLiquidationBonus', type: 'uint256' },
                    { internalType: 'uint256', name: 'reserveFactor', type: 'uint256' },
                    { internalType: 'bool', name: 'usageAsCollateralEnabled', type: 'bool' },
                    { internalType: 'bool', name: 'borrowingEnabled', type: 'bool' },
                    { internalType: 'bool', name: 'stableBorrowRateEnabled', type: 'bool' },
                    { internalType: 'bool', name: 'isActive', type: 'bool' },
                    { internalType: 'bool', name: 'isFrozen', type: 'bool' },
                    { internalType: 'uint128', name: 'liquidityIndex', type: 'uint128' },
                    { internalType: 'uint128', name: 'variableBorrowIndex', type: 'uint128' },
                    { internalType: 'uint128', name: 'liquidityRate', type: 'uint128' },
                    { internalType: 'uint128', name: 'variableBorrowRate', type: 'uint128' },
                    { internalType: 'uint128', name: 'stableBorrowRate', type: 'uint128' },
                    { internalType: 'uint40', name: 'lastUpdateTimestamp', type: 'uint40' },
                    { internalType: 'address', name: 'aTokenAddress', type: 'address' },
                    { internalType: 'address', name: 'stableDebtTokenAddress', type: 'address' },
                    { internalType: 'address', name: 'variableDebtTokenAddress', type: 'address' },
                    { internalType: 'address', name: 'interestRateStrategyAddress', type: 'address' },
                    { internalType: 'uint256', name: 'availableLiquidity', type: 'uint256' },
                    { internalType: 'uint256', name: 'totalPrincipalStableDebt', type: 'uint256' },
                    { internalType: 'uint256', name: 'averageStableRate', type: 'uint256' },
                    { internalType: 'uint256', name: 'stableDebtLastUpdateTimestamp', type: 'uint256' },
                    { internalType: 'uint256', name: 'totalScaledVariableDebt', type: 'uint256' },
                    { internalType: 'uint256', name: 'priceInMarketReferenceCurrency', type: 'uint256' },
                    { internalType: 'address', name: 'priceOracle', type: 'address' },
                    { internalType: 'uint256', name: 'variableRateSlope1', type: 'uint256' },
                    { internalType: 'uint256', name: 'variableRateSlope2', type: 'uint256' },
                    { internalType: 'uint256', name: 'stableRateSlope1', type: 'uint256' },
                    { internalType: 'uint256', name: 'stableRateSlope2', type: 'uint256' },
                    { internalType: 'uint256', name: 'baseStableBorrowRate', type: 'uint256' },
                    { internalType: 'uint256', name: 'baseVariableBorrowRate', type: 'uint256' },
                    { internalType: 'uint256', name: 'optimalUsageRatio', type: 'uint256' },
                    { internalType: 'bool', name: 'isPaused', type: 'bool' },
                    { internalType: 'uint128', name: 'isolationModeTotalDebt', type: 'uint128' },
                    { internalType: 'uint256', name: 'debtCeiling', type: 'uint256' },
                    { internalType: 'uint256', name: 'debtCeilingDecimals', type: 'uint256' },
                    { internalType: 'uint8', name: 'eModeCategoryId', type: 'uint8' },
                    { internalType: 'uint256', name: 'borrowCap', type: 'uint256' },
                    { internalType: 'uint256', name: 'supplyCap', type: 'uint256' },
                    { internalType: 'bool', name: 'eModeCategoryEnabled', type: 'bool' },
                    { internalType: 'uint16', name: 'eModeLtv', type: 'uint16' },
                    { internalType: 'uint16', name: 'eModeLiquidationThreshold', type: 'uint16' },
                    { internalType: 'uint16', name: 'eModeLiquidationBonus', type: 'uint16' },
                    { internalType: 'address', name: 'eModePriceSource', type: 'address' },
                    { internalType: 'string', name: 'eModeLabel', type: 'string' },
                    { internalType: 'bool', name: 'borrowableInIsolation', type: 'bool' },
                ],
                internalType: 'struct IUiPoolDataProvider.AggregatedReserveData[]',
                name: '',
                type: 'tuple[]',
            },
            {
                components: [
                    { internalType: 'uint256', name: 'marketReferenceCurrencyUnit', type: 'uint256' },
                    { internalType: 'int256', name: 'marketReferenceCurrencyPriceInUsd', type: 'int256' },
                    { internalType: 'int256', name: 'networkBaseTokenPriceInUsd', type: 'int256' },
                    { internalType: 'uint8', name: 'networkBaseTokenPriceDecimals', type: 'uint8' },
                ],
                internalType: 'struct IUiPoolDataProvider.BaseCurrencyInfo',
                name: '',
                type: 'tuple',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
] as const;